name: build-and-deploy-project
run-name: ${{github.actor}} started build and deploy action
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
  docker-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build & push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: as9721/rso-data-aggregation
          tags: latest
          registry: Dockerfile.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}
